### ISSUE TITLE
Notification of broken hardware: left hand power board 

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-hardware-manual#15]
The power connector on this board is damaged (see attached pictures). This was temporarily fixed to perform pre-IROS experiments, but a more permanent solution might be required. This board is currently disconnected.

![img_20170306_190850](https://cloud.githubusercontent.com/assets/1451819/23623460/70255226-02a2-11e7-8b8d-f43380e51d9a.jpg)
![img_20170306_190859](https://cloud.githubusercontent.com/assets/1451819/23623461/7025b59a-02a2-11e7-86a1-3ea2cdd1b440.jpg)

----
Note: this issue is just an announcement, not a criticism. The work of the Teo hardware team is much appreciated and required to keep Teo in good shape, and we should all thank them. :clap: :clap:

----

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#5
