### ISSUE TITLE
Notification of broken hardware: left hand controller board 

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-hardware-manual#16]
A capacitor on this board is damaged (see attached picture). Some testing might be required to determine if there exists further damage on this board. I suggest not attaching this board to Teo until fixed, to avoid possible side-effects.

![img_20170306_190828](https://cloud.githubusercontent.com/assets/1451819/23623705/4bd9ca36-02a3-11e7-98dc-aaf5f631ffd9.jpg)

----
Note: this issue is just an announcement, not a criticism. The work of the Teo hardware team is much appreciated and required to keep Teo in good shape, and we should all thank them. :clap: :clap:

----

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#4
