### ISSUE TITLE
This repo needs lots of improvements to become a teo-hardware-manual

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-hardware-manual#17]
This repo needs lots of improvements to become a teo-hardware-manual

**Comment by David-Estevez** [comment]
I was working with Pedro to upload at least a PDF version of the schematics of the PCBs in Teo, so that they are available when needed by Teo users.

#18 is the reference issue for this.

**Comment by jgvictores** [comment]
Duplicate of #4
