### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-hardware-manual#22]
We should at least have a list of JR3 model, etc...

**Comment by rsantos88** [comment]
@jgvictores what do you want exactly to put here?
Do you want documentation of all of TEO hardware, like JR3 model, DRIVERs model, CUIs model..?

**Comment by jgvictores** [comment]
I've created [bill-of-materials.md](https://github.com/roboticslab-uc3m/teo-hardware-manual/blob/11048c21af9476147a4de65d8b4d477c018bc656/bill-of-materials.md) and included it in the gitbook summary. The task would be to fill in the model, and whatever else (links to datasheets, etc). Feel free to modify the table according to needs.

**Comment by rsantos88** [comment]
5 devices [added](https://github.com/roboticslab-uc3m/teo-hardware-manual/blob/master/bill-of-materials.md)

**Comment by jgvictores** [comment]
Looks really good,  @rsantos88 thanks!!
