### ISSUE TITLE
Pieza rota del antebrazo (brazo derecho)

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-hardware-manual#23]
Se ha roto el antebrazo del brazo derecho (pieza impresa 3D) por lo que en este momento se encuentra inutilizable el brazo entero. A espera de reparación.

![whatsapp image 2017-11-23 at 15 17 48](https://user-images.githubusercontent.com/15872457/33177722-f4bfc7b6-d063-11e7-98b6-927bfa3432ba.jpeg)

**Comment by jgvictores** [comment]
Blocking several, such as https://github.com/roboticslab-uc3m/teo-main/issues/22.

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#2
