### ISSUE TITLE
Add motor models to BOM

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-hardware-manual#25]
As a follow-up of #22, add motor models to https://github.com/roboticslab-uc3m/teo-hardware-manual/blob/master/bill-of-materials.md

**Comment by rsantos88** [comment]
done (5800399b21e7d2883000269c1b8d828392900c09)

**Comment by jgvictores** [comment]
Great, @rsantos88 Thanks a lot!!!
