### ISSUE TITLE
Pegar pieza de sujeción del encoder axial de la pierna derecha

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-hardware-manual#27]
Pegar pieza de sujeción del encoder axial de la pierna derecha:

![image](https://user-images.githubusercontent.com/15872457/34156956-bacd09b8-e4bf-11e7-89cd-8e2a6e2b9ec6.png)

**Comment by rsantos88** [comment]
Arreglado. Gracias @AlvaroMartinezR

**Comment by AlvaroMartinezR** [comment]
Bien que la cerraste tú para llevarte los internet points

**Comment by jgvictores** [comment]
> @jgvictores assigned @AlvaroMartinezR just now

@David-Estevez nos lo puede confirmar, creo que http://robots.uc3m.es/contributors/index.html va por assign.

**Comment by rsantos88** [comment]
:joy::joy::joy::joy:
@AlvaroMartinezR maldito, la próxima no te doy las gracias por echar el loctite

**Comment by David-Estevez** [comment]
Están ordenadas por quién las cierra

**Comment by jgvictores** [comment]
Ah ok, thanks!
