### ISSUE TITLE
Teo da calambrazos :zap: :zap:

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-hardware-manual#30]
Suele ser bastante habitual que, cada vez se toca a Teo, recibir una descarga electrostática :zap:
Please, fix this problem :-)

**Comment by smcdiaz** [comment]
¿Es TEO el que te los da a ti? ¿o eres tú el que se los da a TEO?

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#11
