### ISSUE TITLE
Request: accessible hardware documentation for robot users

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-hardware-manual#4]
During the incidents described in #3  we had a difficult time figuring what the correct connections were for some of Teo boards.

To avoid further damage, it would also had been very useful to have the schematics (and later modifications) of those boards, to ensure that hardware hotfixes don't break more than they fix.

I propose the creation of an updated hardware reference guide / repository with all these resources.

(Migrated from https://github.com/roboticslab-uc3m/teo-body/issues/96)

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-developer-manual#31
