### ISSUE TITLE
Avoid short-circuits in hand power boards

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-hardware-manual#5]
Current version of the hand power boards is manufactured in bare copper prototype boards, which are prone to short-circuits and other human errors. Issue #3  is an example of such incidents.

A very simple solution would be to manufacture the current design in a proper production PCB, with soldermask  and silkscreen to prevent accidents.

(Migrated from https://github.com/roboticslab-uc3m/teo-body/issues/97)

**Comment by smcdiaz** [comment]
A very simple solution is to close the UC3M PCB prototyping office or not to order PCB to this service. This PCB was manufactured several years ago.. A new versión of the hand electronics is being designed. Then, it will be removed.

**Comment by David-Estevez** [comment]
This issue was not referred to prototyping, but to the final validated design. IMHO, for prototyping is ok to use the UC3M PCB prototyping office to manufacture a bare copper board. But once we have a stable version, which is the one currently in use, it should be manufactured in a proper board because of the following reasons:

* Manufacturing a proper PCB from a Chinese manufacturer (e.g. [Seeedstudio](https://www.seeedstudio.com/fusion.html)) is very cheap.
* The design is already done and validated with the prototype, so no extra work is required to order these boards.
* The cost of damaging the robot by accident could be much higher than the cost of installing these boards, for instance, if the force sensors or other devices connected to this board are damaged.

But, as always, this was just a kind suggestion for a possible improvement for our beloved Teo from the user's point of view :smile:

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#13
