### ISSUE TITLE
Add blinking lights

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-hardware-manual#6]
As the TV reporters always say, blinking lights make the robot cooler.

Juan said on Feb 20, 2016

@David-Estevez We'll report this ASAP at the next ASROB meeting. The (rd)-research LED matrix know-how may be reusable. It would be a pity for such a feature to go AWOL.

(Migrated from https://github.com/roboticslab-uc3m/teo-body/issues/36)

**Comment by rsantos88** [comment]
Continuing with this forgotten idea, I propose to put a vumeter  ([see this example](https://www.youtube.com/watch?v=kqBhTVXhtGk)) as a mouth, to give the impression that he moves his mouth when he speaks like the mythical [Short circuit](https://www.youtube.com/watch?v=WjeptaI2T8E). 
I think it can be very cool!!

**Comment by PeterBowman** [comment]
> I propose to put a vumeter (see this example) as a mouth, to give the impression that he moves his mouth when he speaks

["Michael, look out!"](https://youtu.be/VKCiJhA7qVo)

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#12
