### ISSUE TITLE
[CuiAbsoluteEncoder] PIC 125 doesn't respond

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-hardware-manual#7]
El encoder 125 no responde al ejecutar el launch.
Se ruega al personal cualificado que arregle el problema lo antes posible.

Un saludo.
Raúl

(Migrated from https://github.com/roboticslab-uc3m/teo-body/issues/86)

**Comment by rsantos88** [comment]
Cierro Issue
