### ISSUE TITLE
Add It2 info on this repo from info given on roboticslab-uc3m/QA#6

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-hardware-manual#8]
Add It2 info on this repo from info given on https://github.com/roboticslab-uc3m/QA/issues/6

**Comment by smcdiaz** [comment]
Do you mean the values for each joint? Or the procedure?

**Comment by jgvictores** [comment]
Hi!

I put this issue more like a reminder to myself that there's some valuable insight in https://github.com/roboticslab-uc3m/QA/issues/6 and it should be given visibility in this repo.

Anyway, all contributions are always welcome! It would be great to have both the current values for each joint, as well as the procedures here!

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-developer-manual#30
